30 add logic for fetching and updating user information section
vsaIT/vsait.org pull request #31
Opened 2023-01-19 15:50 UTC by WilliamHLe

closes #30 

Har bare lagt til styledSwal og wrappet en funksjon i usecallback siden sist du reviewa.

2023-01-19 17:45 UTC, Shirajuki requested changes
Looks good so far nicenice!
It seems that there's also some merge conflicts that needs to be done before merge, you got this! :)

2023-01-19 17:45 UTC, Shirajuki commented on lib/components/Card.tsx
>    // Can wrap with useCallback
Can remove this comment now ;)

2023-01-19 17:45 UTC, Shirajuki commented on lib/components/Card.tsx
> +          window.location.href = '/500';
`StyledSwal.fire` under vil kjøre samtidig som denne linjen. Flytt denne inn i `.then()` chain på `StyledSwal.fire`

2023-01-19 17:45 UTC, Shirajuki commented on lib/components/Card.tsx
> +            text: 'Ser ut som det var noe som gikk galt',
Legg til en timer slik at denne automatisk lukkes også

2023-01-19 17:45 UTC, Shirajuki commented on lib/components/Card.tsx
> +  }, [user]);
`[user, setValue]` på dependencies

2023-01-19 17:45 UTC, Shirajuki commented on lib/components/Navigation.tsx
> +        <Link href="/profil">
`/profile` 😠

2023-01-19 17:45 UTC, Shirajuki commented on lib/components/Navigation.tsx
> +              router.pathname.includes('profil')
`/profile` her også😠

2023-01-19 17:45 UTC, Shirajuki commented on pages/events/[eventid].tsx
> +                                <Link href="/profil">
`/profile` 😠

2023-01-19 17:45 UTC, Shirajuki commented on pages/profil.tsx
> +const Profil: NextPage = () => {
It's `Profile` 😡

2023-01-19 17:45 UTC, Shirajuki commented on pages/profil.tsx
> +    console.log(user, fetching);
Hele denne `useEffect` med `console.log` kan slettes :)

2023-01-19 17:45 UTC, Shirajuki commented on pages/profil.tsx
> +            <>'Loading or not authenticated...'</>
Vurder å gjør om dette til en SkeletonLoader også

2023-01-22 17:22 UTC, WilliamHLe commented on pages/profil.tsx
> +            <>'Loading or not authenticated...'</>
Gjør det til slutt når alle de andre seksjonene er på plass

2023-01-26 15:22 UTC, Shirajuki approved these changes
LGTM

2023-01-26 22:00 UTC, merged