32 add logic for fetching membership section
vsaIT/vsait.org pull request #36
Opened 2023-01-28 16:58 UTC by WilliamHLe

closing #32

2023-01-28 17:00 UTC, WilliamHLe commented on lib/components/Card.tsx
> +  const showActiveMembership = () => {
forutsetter at neste års medlemskap blir lagt til hver høst

2023-01-28 17:01 UTC, WilliamHLe commented on lib/components/Card.tsx
> +  const showActiveMembership = () => {
Kanskje mer ryddig og sette denne funksjonen et annet sted, men vet ikke hvor?

2023-01-28 20:05 UTC, Shirajuki requested changes
LGTM

2023-01-28 20:05 UTC, Shirajuki commented on pages/api/memberships/index.ts
> +const handler = async (req: NextApiRequest, res: NextApiResponse) => {
Dette er implementert med litt mer detalj og error handling på #34 også, men kan merge inn din først så fikser jeg conflict etter hvert. :)

2023-01-28 20:05 UTC, Shirajuki commented on lib/components/Card.tsx
> +  const showActiveMembership = () => {
Dette kan faktisk flyttes til `utils.ts`. Ser også at du har lagt til select av membership på `/api/users/[userid]` endepunktet, og bruker også `user.membership`. Kunne du ikke bare ha brukt dette direkte istedet for parsing av alt det her?

Medlemskapsår er som skoleår og går fra aug til neste aug igjen. Dvs. medlemsskapet fra 2022.08.01 - 2023.08.01 er 2022/2023. Har ikke noe å si om man registrerer på året 2022 (100kr) eller 2023 (50kr). Vil uansett alltid være 2022/2023 når man betaler medlemsskapet i den timerangen.

Se `/pages/index.tsx` linje 55 til 65 f.eks.

2023-01-28 20:05 UTC, Shirajuki commented on pages/api/memberships/index.ts
> +  if (!session || !session?.user)
Burde sjekke om brukeren er admin også btw, har egt. ikke noe å si tho, men bare for å gjøre det riktig hehe :P

2023-01-28 20:05 UTC, Shirajuki commented on pages/api/user/[userid].ts
> +            membership: true,
Hadde sluppet å kjøre `.reverse()` når du henter ut membership om du hadde tatt
```js
membership: {
    orderBy: {
        year: 'desc',
    },
},
```

2023-02-01 19:54 UTC, WilliamHLe commented on lib/components/Card.tsx
> +  const showActiveMembership = () => {
prøvde og gjenbruke det du gjorde på forsiden

2023-02-01 19:58 UTC, WilliamHLe commented
Fiksa på membership status og prøvde å gjenbruke det du gjorde på forsiden. For membership apiet så lar jeg det være siden du har implementert det i en annen branch.

2023-02-02 00:21 UTC, Shirajuki commented
> Fiksa på membership status og prøvde å gjenbruke det du gjorde på forsiden. For membership apiet så lar jeg det være siden du har implementert det i en annen branch.

Tror du har glemt å pushe endringene kanskje, hehe? Har vært noen ganske store endringer i kodebasen også. Husk å fix konfliktene etter merge ;)

2023-02-02 00:39 UTC, WilliamHLe commented
@Shirajuki ok pushet nå hehe

2023-02-02 13:34 UTC, Shirajuki approved these changes
Very nice! 😊

2023-02-02 17:32 UTC, merged